# This workflow will build the application image.
name: build app

on:
  pull_request:
    branches: [dev]

jobs:
  open-shift:
    name: Deploy to OC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install oc
        uses: redhat-actions/oc-installer@v1.1
      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1.2
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true    
      - name: Test
        run: |
          oc api-resources
